### ISSUE TITLE
未安装应用程序

### ISSUE THREAD

**Issue by KingMing2017** [rickdynasty/TwsPluginFramework#2]
安装TwsPluginDemo，出现机器人 ，但点击app，提示“未安装应用程序”

**Comment by tinghaoMa** [comment]
我也是 未安装应用程序  还有为什么不出一个as版本 ？

**Comment by rickdynasty** [comment]
工程里面的Demo不是通常的app，这里是插件apk，因为有shareUI的绑定 不能直接运行
你直接跑 TwsPluginHost.apk这个 是包括插件框架的宿主应用，里面可以动态安装卸载插件应用
