### ISSUE TITLE
今天试了半天,连个demo都没跑起来.

### ISSUE THREAD

**Issue by a437936609** [rickdynasty/TwsPluginFramework#7]
转换为AS项目,一大堆提示错误,attr中name重复.还有个资源文件里边定义的public-padding参数报错,等等.希望有时间能把接入流程简化下.这样接入花费的代价貌似有点大.

**Comment by Hiram-Y** [comment]
都没有提交build.gradle 文件不知道为什么？

**Comment by Hiram-Y** [comment]
用eclipse开发的

**Comment by a437936609** [comment]
请问是只支持在EC下使用这个吗

**Comment by aoldcat** [comment]
这跟limpoxe的APF不是一个么？

**Comment by rickdynasty** [comment]
你需要用pluginCore那个jar包就行

**Comment by rickdynasty** [comment]
除pluginCore之前 其他的都是demo工程，只是这这些demo工程我是跑在eclipse下面【sorry 当前公司还没切换到AS下面 也没抽时间来整理，过一小段时间我会整理一下 切到AS环境】
如果要使用 只需要用pluginCore.jar那个插件框架jar包就行

**Comment by demoface** [comment]
希望能够尽快调整，目前这样只能了解个原理，完全没法接入
